In [ ]:
import pandas as pd
import numpy as np
listay=[78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4]
listax1=[7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10]
listax2=[26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68]
listax3=[ 6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8]
listax4=[60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]

dicc_datos={"y":listay,"x1":listax1,"x2":listax2,"x3":listax3,"x4":listax4}

df=pd.DataFrame(dicc_datos)

print("orginal dataframe:")
display(df)
# replace the "y" column values  with ones
df["y"]=1

print("\nDataFrame with 'y' column converted to ones:")
display(df)

#convert the modified frame to a NumPy array
matrix_ones_y=df.values
print("\nMatrix with 'y' column converted to ones:")
print(matrix_ones_y)

orginal dataframe:


,y,x1,x2,x3,x4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26



DataFrame with 'y' column converted to ones:


,y,x1,x2,x3,x4
0,1,7,26,6,60
1,1,1,29,15,52
2,1,11,56,8,20
3,1,11,31,8,47
4,1,7,52,6,33
5,1,11,55,9,22
6,1,3,71,17,6
7,1,1,31,22,44
8,1,2,54,18,22
9,1,21,47,4,26



Matrix with 'y' column converted to ones:
[[ 1  7 26  6 60]
 [ 1  1 29 15 52]
 [ 1 11 56  8 20]
 [ 1 11 31  8 47]
 [ 1  7 52  6 33]
 [ 1 11 55  9 22]
 [ 1  3 71 17  6]
 [ 1  1 31 22 44]
 [ 1  2 54 18 22]
 [ 1 21 47  4 26]
 [ 1  1 40 23 34]
 [ 1 11 66  9 12]
 [ 1 10 68  8 12]]


In [ ]:
matrix_ones_y

array([[ 1,  7, 26,  6, 60],
       [ 1,  1, 29, 15, 52],
       [ 1, 11, 56,  8, 20],
       [ 1, 11, 31,  8, 47],
       [ 1,  7, 52,  6, 33],
       [ 1, 11, 55,  9, 22],
       [ 1,  3, 71, 17,  6],
       [ 1,  1, 31, 22, 44],
       [ 1,  2, 54, 18, 22],
       [ 1, 21, 47,  4, 26],
       [ 1,  1, 40, 23, 34],
       [ 1, 11, 66,  9, 12],
       [ 1, 10, 68,  8, 12]])

In [ ]:
matrix_ones_y_transpose=matrix_ones_y.T
print(matrix_ones_y_transpose)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 7  1 11 11  7 11  3  1  2 21  1 11 10]
 [26 29 56 31 52 55 71 31 54 47 40 66 68]
 [ 6 15  8  8  6  9 17 22 18  4 23  9  8]
 [60 52 20 47 33 22  6 44 22 26 34 12 12]]


In [ ]:
res = matrix_ones_y_transpose @ matrix_ones_y
res

array([[   13,    97,   626,   153,   390],
       [   97,  1139,  4922,   769,  2620],
       [  626,  4922, 33050,  7201, 15739],
       [  153,   769,  7201,  2293,  4628],
       [  390,  2620, 15739,  4628, 15062]])

In [ ]:
res_inv = np.linalg.inv(res)
res_inv

array([[ 8.20654575e+02, -8.44180186e+00, -8.45777985e+00,
        -8.63453878e+00, -8.28974378e+00],
       [-8.44180186e+00,  9.27104019e-02,  8.56862094e-02,
         9.26373566e-02,  8.44549553e-02],
       [-8.45777985e+00,  8.56862094e-02,  8.75602572e-02,
         8.78666397e-02,  8.55980995e-02],
       [-8.63453878e+00,  9.26373566e-02,  8.78666397e-02,
         9.52014097e-02,  8.63919188e-02],
       [-8.28974378e+00,  8.44549553e-02,  8.55980995e-02,
         8.63919188e-02,  8.40311912e-02]])

In [ ]:
print(res_inv)

[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


In [ ]:
betas = res_inv @ matrix_ones_y_transpose @ np.array(listay)
betas

array([62.4053693 ,  1.55110265,  0.51016758,  0.1019094 , -0.14406103])

In [ ]:
X=matrix_ones_y
X

array([[ 1,  7, 26,  6, 60],
       [ 1,  1, 29, 15, 52],
       [ 1, 11, 56,  8, 20],
       [ 1, 11, 31,  8, 47],
       [ 1,  7, 52,  6, 33],
       [ 1, 11, 55,  9, 22],
       [ 1,  3, 71, 17,  6],
       [ 1,  1, 31, 22, 44],
       [ 1,  2, 54, 18, 22],
       [ 1, 21, 47,  4, 26],
       [ 1,  1, 40, 23, 34],
       [ 1, 11, 66,  9, 12],
       [ 1, 10, 68,  8, 12]])

In [ ]:
ypred = X @ betas
ypred

array([ 78.49523958,  72.7887993 , 105.97093753,  89.32710025,
        95.64924444, 105.2745573 , 104.14866909,  75.67498852,
        91.72165052, 115.618452  ,  81.80901643, 112.32701096,
       111.69433407])

# Pasando de Excel a Pandas:

In [ ]:
import pandas as pd
import numpy as np
listay=[78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4]
listax1=[7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10]
listax2=[26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68]
listax3=[ 6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8]
listax4=[60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 6]

dicc_datos={"y":listay,"x1":listax1,"x2":listax2,"x3":listax3,"x4":listax4}

df=pd.DataFrame(dicc_datos)
df

,y,x1,x2,x3,x4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26


In [ ]:
df["ypred"]=ypred
df

,y,x1,x2,x3,x4,ypred
0,78.5,7,26,6,60,78.495240
1,74.3,1,29,15,52,72.788799
2,104.3,11,56,8,20,105.970938
3,87.6,11,31,8,47,89.327100
4,95.9,7,52,6,33,95.649244
5,109.2,11,55,9,22,105.274557
6,102.7,3,71,17,6,104.148669
7,72.5,1,31,22,44,75.674989
8,93.1,2,54,18,22,91.721651
9,115.9,21,47,4,26,115.618452


In [ ]:
df["y-ypred"]=df["y"]-df["ypred"]
df

,y,x1,x2,x3,x4,ypred,y-ypred
0,78.5,7,26,6,60,78.495240,0.004760
1,74.3,1,29,15,52,72.788799,1.511201
2,104.3,11,56,8,20,105.970938,-1.670938
3,87.6,11,31,8,47,89.327100,-1.727100
4,95.9,7,52,6,33,95.649244,0.250756
5,109.2,11,55,9,22,105.274557,3.925443
6,102.7,3,71,17,6,104.148669,-1.448669
7,72.5,1,31,22,44,75.674989,-3.174989
8,93.1,2,54,18,22,91.721651,1.378349
9,115.9,21,47,4,26,115.618452,0.281548


In [ ]:
df["error^2"]=df["y-ypred"]**2
df

,y,x1,x2,x3,x4,ypred,y-ypred,error^2
0,78.5,7,26,6,60,78.495240,0.004760,0.000023
1,74.3,1,29,15,52,72.788799,1.511201,2.283728
2,104.3,11,56,8,20,105.970938,-1.670938,2.792032
3,87.6,11,31,8,47,89.327100,-1.727100,2.982875
4,95.9,7,52,6,33,95.649244,0.250756,0.062878
5,109.2,11,55,9,22,105.274557,3.925443,15.409100
6,102.7,3,71,17,6,104.148669,-1.448669,2.098642
7,72.5,1,31,22,44,75.674989,-3.174989,10.080552
8,93.1,2,54,18,22,91.721651,1.378349,1.899847
9,115.9,21,47,4,26,115.618452,0.281548,0.079269


In [ ]:
error_cuadratico_total=df["error^2"].sum()
error_cuadratico_total

np.float64(47.86363935049879)

In [ ]:
error_cuadratico_medio=error_cuadratico_total/len(ypred)
error_cuadratico_medio

np.float64(3.6818184115768298)

In [ ]:
raiz_error_cuadratico_medio=error_cuadratico_medio**0.5
raiz_error_cuadratico_medio

np.float64(1.9188065070706921)